### ISSUE TITLE
Cannot load JavaScript file over 130KB

### ISSUE THREAD

**Issue by piglovesyou** [le0pard/elixir_v8#7]
Here is a simple elixir script running totally fine.
```
ElixirV8.create_pool(:main, 10, file: "a.js")
IO.inspect ElixirV8.eval({:global, :main}, "a()")
```
But when the "a.js" gets larger, it shows error like this.
```
[pig@localhost phoenix_react]$ ls -lh a.js ; mix run run.exs
-rw-r--r-- 1 pig pig 130K Feb 25 10:40 a.js
** (exit) exited in: :gen_server.call({:global, :main}, {:checkout, #Reference<0.0.7.2642>, true}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (kernel) global.erl:198: :global.send/2
    (stdlib) gen_server.erl:219: :gen_server.cast/2
    (poolboy) src/poolboy.erl:58: :poolboy.checkout/3
    (poolboy) src/poolboy.erl:74: :poolboy.transaction/3
    run.exs:2: (file)
    (elixir) lib/code.ex:370: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:82: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2

[error] GenServer #PID<0.273.0> terminating
** (MatchError) no match of right hand side value: {:error, {{:badmatch, {:error, :vm_unresponsive}}, [{ElixirV8.VM, :init, 1, [file: 'lib/elixir_v8/vm.ex', line: 19]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
    (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
    (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
    (poolboy) src/poolboy.erl:145: :poolboy.init/3
    (stdlib) gen_server.erl:328: :gen_server.init_it/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.272.0>, {{:badmatch, {:error, {{:badmatch, {:error, :vm_unresponsive}}, [{ElixirV8.VM, :init, 1, [file: 'lib/elixir_v8/vm.ex', line: 19]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}, [{:poolboy, :new_worker, 1, [file: 'src/poolboy.erl', line: 275]}, {:poolboy, :prepopulate, 3, [file: 'src/poolboy.erl', line: 296]}, {:poolboy, :init, 3, [file: 'src/poolboy.erl', line: 145]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: {:state, {#PID<0.273.0>, :poolboy_sup}, :simple_one_for_one, [{:child, :undefined, ElixirV8.VM, {ElixirV8.VM, :start_link, [[file: "a.js"]]}, :temporary, 5000, :worker, [ElixirV8.VM]}], {:set, {:set, 0, 16, 16, 8, 80, 48, {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}, {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}}, 0, 1, [], 0, :poolboy_sup, {ElixirV8.VM, [file: "a.js"]}}
```
It's nicer when it prints kinder error message or document about it in readme.

**Comment by le0pard** [comment]
Try to increase timeout - maybe 5 second not enough for this script.

**Comment by piglovesyou** [comment]
Thank you, but I thought timeout is for `eval/3`, as I tried, it gets error when to `create_pool/3`.

**Comment by piglovesyou** [comment]
I think it's erlang_v8 problem, I'll report there.

**Comment by piglovesyou** [comment]
https://github.com/strange/erlang_v8/issues/5
